language: android
sudo: true
android:
  components:
    - tools
    - platform-tools
    - extra-google-m2repository
    - extra-android-m2repository
addons:
  artifacts:
    paths:
      - $(git ls-files -o | grep libs | tr "\n" ":")

before_install:
install:
  - echo y | sdkmanager "ndk;21.2.6472646"
  - echo y | sdkmanager "cmake;3.10.2.4988404"
  - sdkmanager --update
before_script:

script:
  - make
