language: android
android:
  components:
    - build-tools-26.0.2
    - android-26
    - ndk-bundle
    - cmake-3.10.2.4988404
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'    
addons:
  artifacts:
    paths:
      - $(git ls-files -o | grep libs | tr "\n" ":")
cache:
  directories:
    - $HOME/.android/build-cache
script:
  - make
