language: android
sudo: true
android:
  components:
    - android
    - tools
    - platform-tools
    - build-tools    
addons:
  artifacts:
    paths:
      - $(git ls-files -o | grep libs | tr "\n" ":")

before_install:
install:
before_install:
  - echo y | sdkmanager --licenses
  # - echo y | sdkmanager "ndk"
  - echo y | sdkmanager "ndk-bundle"
  - echo y | sdkmanager "cmake;3.10.2.4988404"
  - sdkmanager --update
before_script:

script:
  - make
