name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Submodules
        uses: textbook/git-checkout-submodule-action@master
        with:
          remote: true
      - shell: bash
        run: mkdir toolchains
      - name: Android NDK toolchain Setup
        uses: ravinderjangra/android-ndk-toolchain-setup@0.2
        with:
          api: 29
          arch: arm64
          install-location: toolchains
          force: true 
      - shell: bash
        run: make
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.1.4
        with:          
          path: ./libs
          if-no-files-found: error
